spring:
    application:
        name: order-management-service

    datasource:
        url: jdbc:postgresql://crossover.proxy.rlwy.net:17164/railway
        username: postgres
        password: YasipCIaWCkaKtgGMhMZOlZFfefHjwQg
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: ${PORT:8080}

jwt:
    secret: f52be42ac5950835ce3cb3d249e8ccb62710350798755b55e15d0215ba4115cc
    access-token:
        expiration-ms: 900000
    refresh-token:
        expiration-ms: 604800000
